### ISSUE TITLE
로직을 Entity에 넣어서 관리해야 하는가 Service에 넣어서 관리해야 하는가

### ISSUE THREAD

**Issue by jungmini0601** [jungmini0601/pay#26]
![image](https://user-images.githubusercontent.com/126523988/229436648-1dcf57ac-9d22-48f1-9093-1f80b36e487d.png)
![image](https://user-images.githubusercontent.com/126523988/229436754-72aa306f-5ad2-445b-bea0-ed11e48f5069.png)

데이터가 엔티티에 있어서 자연스럽게 엔티티 메소드에 로직을 몰아 넣었더니 엔티티가 너무 커지고 있다.

**관련된 코드**
AccountService: https://github.com/jungmini0601/pay/blob/master/src/main/java/com/jungmini/pay/service/AccountService.java
Account: https://github.com/jungmini0601/pay/blob/master/src/main/java/com/jungmini/pay/domain/Account.java

**Comment by jungmini0601** [comment]
**상황정리**

1. 업무 로직상 어차피 필요한 코드이다.
2. 고민해야 하는 포인트는 로직을 Service에서 가져가느냐 Entity에서 가져가느냐이다.

**Comment by kwj1270** [comment]
이슈에 작업한 브랜치 링크가 있으면 좋을 것 같네요

**Comment by jungmini0601** [comment]
> 이슈에 작업한 브랜치 링크가 있으면 좋을 것 같네요

앗 알려주셔서 감사합니다!😊 수정했습니다

**Comment by jungmini0601** [comment]
이슈 내용 최종 정리 완료
